### ISSUE TITLE
Vanila konfigurace založená na czechitas/render

### ISSUE THREAD

**Issue by podlomar** [kodim-cz/kodim-starter-kits#8]

**Comment by FilipChalupa** [comment]
Asi něco jako https://github.com/Czechitas-podklady-WEB/templating-react-demo/blob/main/vite.config.js a `czechitasRenderVitePlugin` se může nahradit za React plugin.

**Comment by FilipChalupa** [comment]
Řeší mimo jiné multisite.

**Comment by podlomar** [comment]
Jj, přesně odtamtud to beru
